<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>MedSestriManipulations</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>MedSestri</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.medsestrimanipulations</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>

	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\medsestr_icon.png" ForegroundFile="Resources\AppIcon\medsestr_icon.png" Color="#2196F3" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\medsestri_splashscreen.png" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		<MauiImage Update="Resources\Images\history.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<AndroidResource Remove="Platforms\Android\Resources\values\strings.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="11.2.0" />
		<PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.60" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.4" />
		<PackageReference Include="Plugin.Firebase.CloudMessaging" Version="3.1.2" />
		<PackageReference Include="Refractored.MvvmHelpers" Version="1.6.2" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
		<GoogleServicesJson Include="google-services.json" />
		<PackageReference Include="Xamarin.AndroidX.SavedState">
			<Version>1.3.1.1</Version>
		</PackageReference>
		<PackageReference Include="Xamarin.AndroidX.SavedState.SavedState.Ktx">
			<Version>1.3.1.1</Version>
		</PackageReference>
		<PackageReference Include="Xamarin.Firebase.Messaging">
			<Version>125.0.0.1</Version>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="CatheterPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="HistoryPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ItemGroup>
		<MauiAsset Update="Resources\Raw\procedures.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</MauiAsset>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Resources\Images\" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<AndroidLinkMode>None</AndroidLinkMode>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
		<AndroidKeyStore>False</AndroidKeyStore>
		<EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<RunAOTCompilation>false</RunAOTCompilation>
	</PropertyGroup>

	<!--<PropertyGroup>
		<AndroidPackageFormat>aab</AndroidPackageFormat>
	</PropertyGroup>-->

</Project>
